# Generated by Django 2.2.8 on 2019-12-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='captions',
            field=models.TextField(blank=True, default='', help_text='Additional text description for this photo.'),
        ),
    ]
