# Generated by Django 2.2.8 on 2019-12-15 07:56

from django.db import migrations
import easy_thumbnails.fields
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20191215_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(help_text='Actual photo media file path.', upload_to=photos.models.get_photo_upload_path),
        ),
    ]
